package com.lantern;
import com.lantern.history.*;import com.lantern.model.Device;import com.lantern.agent.AgentRegistry;import com.lantern.network.*;import com.lantern.ui.ConsoleUI;import com.lantern.web.WebDashboard;import java.nio.file.*;import java.util.*;
public class Lantern{
 private static final int[] DEFAULT_PORTS={20,21,22,23,25,53,80,110,123,135,139,143,443,445,631,1433,1883,3000,3306,3389,5000,5432,5900,6379,8000,8080,8096,8443};
 public static void main(String[]args){ConsoleUI ui=new ConsoleUI();ui.banner();try{NetworkInterfaceInfo n=new NetworkDetector().detect();ui.network(n);int[]ports=parsePorts(args);String oui=parseOui(args);int web=parseWeb(args);DeviceScanner scanner=new DeviceScanner(ports,oui);AgentRegistry agents=AgentRegistry.fromArgs(args);HistoryStore history=new HistoryStore(Paths.get("data","history.csv"));WebDashboard dash=new WebDashboard(web, agents);dash.start();List<Device>current=scan(ui,scanner,n);agents.enrich(current);history.saveScan(current);ui.results(current);dash.update(n,current,List.of());while(true){System.out.println("\nCommands: [d] details  [r] rescan  [m] monitor  [h] history  [w] dashboard  [q] quit");System.out.print("lantern> ");String c=new Scanner(System.in).nextLine().trim().toLowerCase();switch(c){case"d"->{Device d=ui.select(current);ui.details(d);}case"r"->{List<Device>old=current;current=scan(ui,scanner,n);agents.enrich(current);history.saveScan(current);List<NetworkEvent>ev=new NetworkMonitor().compare(old,current);ui.results(current);ui.events(ev);dash.update(n,current,ev);}case"m"->monitor(ui,scanner,n,current,history,dash,agents);case"h"->history.recentLines(20).forEach(System.out::println);case"w"->System.out.println("Dashboard: http://127.0.0.1:"+web);case"q","exit"-> {System.out.println("Goodbye.");return;}default->System.out.println("Unknown command.");}}}catch(InterruptedException e){Thread.currentThread().interrupt();System.err.println("Scan interrupted.");}catch(Exception e){System.err.println("Lantern error: "+e.getMessage());e.printStackTrace();}}
 private static List<Device>scan(ConsoleUI ui,DeviceScanner s,NetworkInterfaceInfo n)throws InterruptedException{System.out.println("Scanning "+n.getNetworkAddress()+"/"+n.getPrefixLength()+"...");return s.scan(n,ui::progress);}
 private static void monitor(ConsoleUI ui,DeviceScanner s,NetworkInterfaceInfo n,List<Device>cur,HistoryStore h,WebDashboard d,AgentRegistry agents)throws InterruptedException{System.out.println("Monitor mode. Rescanning every 10 seconds. Press Ctrl+C to stop.");List<Device>old=cur;NetworkMonitor m=new NetworkMonitor();while(true){Thread.sleep(10000);List<Device>next=scan(ui,s,n);agents.enrich(next);h.saveScan(next);List<NetworkEvent>ev=m.compare(old,next);ui.events(ev);ui.results(next);d.update(n,next,ev);old=next;}}
 private static int[]parsePorts(String[]a){for(String x:a)if(x.startsWith("--ports=")){String[]p=x.substring(8).split(",");int[]o=new int[p.length];int c=0;for(String z:p)try{int v=Integer.parseInt(z.trim());if(v>0&&v<65536)o[c++]=v;}catch(Exception ignored){}return c==0?DEFAULT_PORTS:Arrays.copyOf(o,c);}return DEFAULT_PORTS;}
 private static String parseOui(String[]a){for(String x:a)if(x.startsWith("--oui="))return x.substring(6);return null;}private static int parseWeb(String[]a){for(String x:a)if(x.startsWith("--web="))try{return Integer.parseInt(x.substring(6));}catch(Exception ignored){}return 8765;}
}
